<a href="https://colab.research.google.com/github/jorgeponcer-svg/Series-Temporales/blob/main/Agrupando_por_frecuencia_diferente.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importar librerías

In [ ]:
import pandas as pd
# set max columns to display
pd.set_option('display.max_columns', 50)

# Dataset

El dataset que vamos a usar proviene de: <a href="https://data.worldbank.org/"> World Bank Open data </a> y trata sobre datos de precios "crowd-source" obtenidos de 15 países diferentes. Para más detalles sobre los datos: <a href="https://datacatalog.worldbank.org/dataset/crowdsourced-price-data-collection-pilot"> Crowdsourced Price Data Collection Pilot </a>. Para este ejercicio en particular, vamos a ver los datos de Argentina.

In [ ]:
# importando los datos
initial_data = pd.read_csv('/content/arg-crowdsourcedpdcpilot02_final_obs_all_clean.csv', parse_dates=['created_at'], on_bad_lines='skip')

In [ ]:
initial_data.head(5)

,item_name,item_code,bh_name,bh_code,created_at,brand,created_fr_lat,created_fr_lon,obs_uid,size,quantity,total_size,converted_total_size,normalized_total_size,price,normalized_price,fx_usd,fx_local,normalized_price_usd,normalized_price_local,currency,units,reference_unit_of_measurement,reference_quantity,place_uuid,place_name,place_lat,place_long,store_type,country,l0,l1,l2,l0_geo,l1_geo,l2_geo,l3_geo,pop_density,dist_l2,city_radius,metadata_json
0,"Men's haircut, barber shop",111211101,Hairdressing salons and personal grooming esta...,1112111.0,2016-06-06 14:57:57.493,NaN,-34.612083,-58.424259,0003134e-cb5d-4a81-bd25-770d67c4759b,1.0,1,1.0,1.0,1.0,50.00,50.000,13.938950,13.938950,3.587071,50.000,ARS,piece(s),Service,1.0,0a9723ea-dcdd-478d-8928-4b019ac6b2d5,peluqueria gaacon 124,-34.610687,-58.424356,private_service_provider,AR,Argentina,Buenos Aires,Buenos Aires,Argentina,Ciudad de Buenos Aires,Distrito Federal,Buenos Aires,323.583880,2.397569,50,"{ ""price_includes_charges_value"" : ""yes"" }"
1,"Sardines, tinned, with skin, in vegetable oil,...",110113201,Preserved or processed fish and seafood,1101132.0,2016-04-19 17:47:57.557,GV,-31.466946,-64.163376,0006d339-1ef4-4d27-9f99-aac6773c4633,160.0,1,160.0,160.0,0.8,29.30,36.625,14.163950,14.163950,2.585790,36.625,ARS,g,Gram,200.0,7db0b4f4-eb09-4f0c-bbb5-c5d052064f49,walmart hoggins,-31.464056,-64.163222,small_medium_shop,AR,Argentina,Córdoba,Cordoba,Argentina,Córdoba,Capital,Córdoba,40.096850,6.264624,20,"{ ""tin_can_packaging_value"" : ""yes"", ""sardines..."
2,"Broken rice, 25%, BNR",110111106,Rice,1101111.0,2016-03-08 18:43:48.048,jumbo,-34.590607,-58.408207,0008d632-8fee-4957-972a-ceb1307e06b9,1.0,1,1.0,1.0,1.0,12.49,12.490,15.446950,15.446950,0.808574,12.490,ARS,kg,Kilogram,1.0,61a47c51-c47c-4f2a-8f6b-914ff938218c,DISCO Av. Santa Fe 3047 Palermo,-34.590394,-58.408558,NaN,AR,Argentina,Buenos Aires,Buenos Aires,Argentina,Ciudad de Buenos Aires,Distrito Federal,Buenos Aires,321.490285,4.491375,50,"{ ""packaged_unpackaged_value"" : ""prepacked"", ""..."
3,"Men's shirt, WKB-M",110312103,Garments,1103121.0,2016-04-10 17:33:59.277,george,-31.395527,-64.259949,0008ec67-df92-4d7a-a859-b9d0bb95cacb,1.0,1,1.0,1.0,1.0,349.00,349.000,14.461316,14.461316,24.133350,349.000,ARS,piece(s),Piece,1.0,6a9f0ff13a333d85609d738923db6c49364c0e38,Walmart Córdoba Oeste Colón,-31.394419,-64.260132,small_medium_shop,AR,Argentina,Córdoba,Cordoba,Argentina,Córdoba,Capital,Córdoba,36.855019,6.533218,20,"{ ""brand_value"" : ""george"", ""adult_child_value..."
4,"Vacuum cleaner, WKB-M",110531111,Major household appliances whether electric or...,1105311.0,2016-03-24 21:36:48.824,philips,-34.674744,-58.367367,0008f63c-11f6-4f3b-9277-77a11288f361,1.0,1,1.0,1.0,1.0,1799.00,1799.000,14.502950,14.502950,124.043729,1799.000,ARS,piece(s),Piece,1.0,a09e2842d54603845a7d84859854729151e485cc,Walmart Avellaneda,-34.676401,-58.365980,small_medium_shop,AR,Argentina,Buenos Aires,Buenos Aires,Argentina,Buenos Aires,Avellaneda,Crucecita,118.042055,10.591399,50,"{ ""vaccuum_features_value"" : ""[automatic_cord_..."

In [ ]:
# Vamos a seleccionar un conjunto de columnas para el ejercicio
columns_to_select = ['item_name', 'item_code', 'created_at', 'size', 'quantity', 'price', 'store_type']

In [ ]:
data = initial_data[columns_to_select]
data.head(5)

,item_name,item_code,created_at,size,quantity,price,store_type
0,"Men's haircut, barber shop",111211101,2016-06-06 14:57:57.493,1.0,1,50.00,private_service_provider
1,"Sardines, tinned, with skin, in vegetable oil,...",110113201,2016-04-19 17:47:57.557,160.0,1,29.30,small_medium_shop
2,"Broken rice, 25%, BNR",110111106,2016-03-08 18:43:48.048,1.0,1,12.49,NaN
3,"Men's shirt, WKB-M",110312103,2016-04-10 17:33:59.277,1.0,1,349.00,small_medium_shop
4,"Vacuum cleaner, WKB-M",110531111,2016-03-24 21:36:48.824,1.0,1,1799.00,small_medium_shop

In [ ]:
#Ordenamos los datos con respecto al tiempo, porque están desordenados
data=data.sort_values(by=['created_at'])
data.head(5)

,item_name,item_code,created_at,size,quantity,price,store_type
7501,"Wrist-watch, men's, CITIZEN Eco-Drive BM6060",111231102,2015-12-14 18:10:03.587,1.0,1,3470.00,NaN
13293,"Men's lace-up shoes, WKB-L",110321101,2015-12-14 18:12:04.662,1.0,1,1900.00,NaN
33893,"Dinner plate, flat, porcelain, WKB-L",110541104,2015-12-14 18:24:47.561,1.0,1,79.90,NaN
22728,"Cooking salt, WKB",110119102,2015-12-14 19:59:06.881,500.0,1,5.89,NaN
19456,"Water, still, large bottle, WKB",110122101,2015-12-14 19:59:57.011,2000.0,1,10.09,small_medium_shop

# Aquí tienes información sobre todos los tipos de frecuencias que se pueden usar

https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases

# Combinando los datos en base a distintos intervalos de frecuencia

### Vamos a usar la función resample()
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html

## Agregando en Horas

In [ ]:
# Aseguramos que la columna sea datetime y luego aplicamos resample con la frecuencia correcta ('h')
data = data.copy()
data['created_at'] = pd.to_datetime(data['created_at'], errors='coerce')
data.resample('h', on='created_at').price.sum().head(5)

created_at
2015-12-14 18:00:00    5449.90
2015-12-14 19:00:00      15.98
2015-12-14 20:00:00      66.98
2015-12-14 21:00:00       0.00
2015-12-14 22:00:00       0.00
Name: price, dtype: float64

In [ ]:
# Por defecto, el tiempo de inicio para frecuencia horaria es a las XX:00:00. Pero esto se puede cambiar con el parámetro 'offset'
data.resample('h', on='created_at', offset='15Min10s').price.sum().head(5)

created_at
2015-12-14 17:15:10    5370.00
2015-12-14 18:15:10      79.90
2015-12-14 19:15:10      64.56
2015-12-14 20:15:10      18.40
2015-12-14 21:15:10       0.00
Name: price, dtype: float64

In [ ]:
# Si queremos 2 horas, 5 horas, u otro número de horas, sería poniendo '2h', '5h', etc.
data.resample('5h', on='created_at', offset='15Min10s').price.sum().head(5)

created_at
2015-12-14 15:15:10    5514.46
2015-12-14 20:15:10      18.40
2015-12-15 01:15:10       0.00
2015-12-15 06:15:10       0.00
2015-12-15 11:15:10     617.58
Name: price, dtype: float64

## Agregando en Minutos

In [ ]:
# Vamos a ver cada 5 minutos
data.resample('5min', on='created_at').price.sum().head(5)

created_at
2015-12-14 18:10:00    5370.0
2015-12-14 18:15:00       0.0
2015-12-14 18:20:00      79.9
2015-12-14 18:25:00       0.0
2015-12-14 18:30:00       0.0
Name: price, dtype: float64

## Agregando en Segundos

In [ ]:
# Con el parámetro 's'
data.resample('s', on='created_at').price.sum().head(5)

created_at
2015-12-14 18:10:03    3470.0
2015-12-14 18:10:04       0.0
2015-12-14 18:10:05       0.0
2015-12-14 18:10:06       0.0
2015-12-14 18:10:07       0.0
Name: price, dtype: float64

In [ ]:
# Si queremos en vez de 1 segundo, 10 segundos, 20 segundos, ..., X segundos, solo tenemos que poner '10S', o '20S' o el número de segundos que se quieran
data.resample('10s', on='created_at').price.sum().head(5)

created_at
2015-12-14 18:10:00    3470.0
2015-12-14 18:10:10       0.0
2015-12-14 18:10:20       0.0
2015-12-14 18:10:30       0.0
2015-12-14 18:10:40       0.0
Name: price, dtype: float64

## Agregando en base a Semanas

In [ ]:
data.resample('W', on='created_at').price.sum().head(5)

created_at
2015-12-20     43056.38
2015-12-27     67338.51
2016-01-03     44434.59
2016-01-10     18222.36
2016-01-17    190838.54
Name: price, dtype: float64

In [ ]:
# Por defecto la semana empieza en DOMINGO, pero lo podemos cambiar al día que se quiera, por ejemplo, Lunes
data.resample('W-MON', on='created_at').price.sum().head(5)

created_at
2015-12-14     5532.86
2015-12-21    38507.62
2015-12-28    66863.29
2016-01-04    53924.10
2016-01-11    12608.69
Name: price, dtype: float64

## Agregando con respecto a Meses

In [ ]:
data.resample('M', on='created_at').price.sum()

/tmp/ipykernel_1060/2188889167.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  data.resample('M', on='created_at').price.sum()

created_at
2015-12-31    1.538769e+05
2016-01-31    4.297143e+05
2016-02-29    9.351207e+05
2016-03-31    7.387732e+06
2016-04-30    1.384308e+07
2016-05-31    1.251449e+07
2016-06-30    7.262549e+06
2016-07-31    6.739193e+06
2016-08-31    2.721504e+06
Name: price, dtype: float64

In [ ]:
# Por defecto, los meses se agrupan con respecto al último día del mes. Vamos a ver cómo cambiarlo para empezar en el primer día del mes.
# Es con 'MS' que significa Month Start
data.resample('MS', on='created_at').price.sum()

created_at
2015-12-01    1.538769e+05
2016-01-01    4.297143e+05
2016-02-01    9.351207e+05
2016-03-01    7.387732e+06
2016-04-01    1.384308e+07
2016-05-01    1.251449e+07
2016-06-01    7.262549e+06
2016-07-01    6.739193e+06
2016-08-01    2.721504e+06
Name: price, dtype: float64

## Agregando cuando tenemos varias variables

1. La variable item_code se agrega contando los datos únicos en cada hora.
2. La variable quantity la vamos a agregar sumando todos los valores durante cada hora.
3. La variable price la vamos a agregar sumando todos los valores durante cada hora.

In [ ]:
data.resample('h', on='created_at').agg({'price':'sum', 'quantity':'sum','item_code':'nunique'}).head(5)

                       price  quantity  item_code
created_at
2015-12-14 18:00:00  5449.90         3          3
2015-12-14 19:00:00    15.98         2          2
2015-12-14 20:00:00    66.98         7          4
2015-12-14 21:00:00     0.00         0          0
2015-12-14 22:00:00     0.00         0          0

### Varias variables, cada 30 segundos

In [ ]:
data.resample('30s', on='created_at').agg({'price':'sum', 'quantity':'sum','item_code':'nunique'}).head(5)

                      price  quantity  item_code
created_at
2015-12-14 18:10:00  3470.0         1          1
2015-12-14 18:10:30     0.0         0          0
2015-12-14 18:11:00     0.0         0          0
2015-12-14 18:11:30     0.0         0          0
2015-12-14 18:12:00  1900.0         1          1

### Ahora cada 5 minutos

In [ ]:
data.resample('5min', on='created_at').agg({'price':'sum', 'quantity':'sum','item_code':'nunique'}).head(5)

                      price  quantity  item_code
created_at
2015-12-14 18:10:00  5370.0         2          2
2015-12-14 18:15:00     0.0         0          0
2015-12-14 18:20:00    79.9         1          1
2015-12-14 18:25:00     0.0         0          0
2015-12-14 18:30:00     0.0         0          0

### Ahora cada 5 días y con otras cantidades, por ejemplo:
#### 'mean': media
#### 'min': mínimo
#### 'max': máximo
#### 'count': cuenta todas las filas (la cantidad de datos) en ese intervalo
#### 'nunique': cuenta las cantidades únicas (sin repetición) en ese intervalo

In [ ]:
data.resample('5D', on='created_at').agg({'price':'min', 'quantity':'max','item_code':'count'}).head(5)

            price  quantity  item_code
created_at
2015-12-14   4.99        12         72
2015-12-19   5.99         4         45
2015-12-24   7.30         4         25
2015-12-29   6.99        20         50
2016-01-03   5.19        12         66

# Agrupando datos dependiendo de los valores de una de las variables

### Vamos a usar la función Grouper()
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Grouper.html

## Agregando el precio, para cada tipo de tienda (store_type), con frecuencia semanal.

In [ ]:
data.groupby([pd.Grouper(key='created_at', freq='W'), 'store_type']).price.sum().head(15)

created_at  store_type
2015-12-20  other                          34300.00
            public_semi_public_service       833.90
            small_medium_shop               1206.04
2015-12-27  small_medium_shop                923.09
            specialized_shop               65164.00
2016-01-03  small_medium_shop                355.10
            specialized_shop               41922.00
2016-01-10  other                           8300.00
            small_medium_shop                412.55
            specialized_shop                3979.00
2016-01-17  market                           170.78
            other                         144341.00
            private_service_provider         220.00
            public_semi_public_service       271.84
            small_medium_shop              20908.29
Name: price, dtype: float64

## Lo mismo, con frecuencia mensual

In [ ]:
data.groupby([pd.Grouper(key='created_at', freq='ME'), 'store_type']).price.sum().head(15)

created_at  store_type
2015-12-31  other                          34300.00
            public_semi_public_service       833.90
            small_medium_shop               2484.23
            specialized_shop              107086.00
2016-01-31  market                           473.75
            other                         314741.00
            private_service_provider         325.00
            public_semi_public_service       276.79
            small_medium_shop              31042.79
            specialized_shop               29648.44
2016-02-29  market                          1974.04
            other                         527950.00
            private_service_provider        1620.00
            public_semi_public_service      1028.52
            small_medium_shop             224633.83
Name: price, dtype: float64

## Frecuencia mensual, pero dependiendo del tipo de item (item_name)

In [ ]:
data.groupby([pd.Grouper(key='created_at', freq='ME'), 'item_name']).price.sum()

created_at  item_name
2015-12-31  Bar soap, solid, SB                                33.17
            Beer, domestic brand, single bottle, WKB           29.79
            Black tea, BL                                      12.00
            Black tea, in bags, WKB                            60.99
            Bread, white, sliced, WKB                          85.45
                                                              ...
2016-08-31  Wheat flour, not self-rising, BL                  150.38
            White sugar, WKB                                  266.47
            Women's haircut, basic hairdresser               7730.00
            Wrist-watch, men's, CITIZEN Eco-Drive BM6060    52205.00
            Yoghurt, plain, WKB                               150.96
Name: price, Length: 1061, dtype: float64

## Agregación múltiple dependiendo del tipo de tienda, con frecuencia mensual.

In [ ]:
data.groupby([pd.Grouper(key='created_at', freq='ME'), 'store_type'])\
    .agg(unique_items=('item_code', 'nunique'),
         total_quantity=('quantity','sum'),
         total_amount=('price','sum')).head(20)

                                       unique_items  total_quantity  \
created_at store_type
2015-12-31 other                                  3               6
           public_semi_public_service             1               1
           small_medium_shop                     27              88
           specialized_shop                       2              20
2016-01-31 market                                 2              12
           other                                  5              43
           private_service_provider               2               2
           public_semi_public_service             2               2
           small_medium_shop                     73             472
           specialized_shop                       7              24
2016-02-29 market                                27              41
           other                                  4              75
           private_service_provider               5              11
           public_semi_public_service             2               5
           small_medium_shop                     77            1032
           specialized_shop                      16              77
2016-03-31 bulk_discount_shop                     2               3
           market                                 5             101
           other                                  6             486
           private_service_provider              13             167

                                       total_amount
created_at store_type
2015-12-31 other                           34300.00
           public_semi_public_service        833.90
           small_medium_shop                2484.23
           specialized_shop               107086.00
2016-01-31 market                            473.75
           other                          314741.00
           private_service_provider          325.00
           public_semi_public_service        276.79
           small_medium_shop               31042.79
           specialized_shop                29648.44
2016-02-29 market                           1974.04
           other                          527950.00
           private_service_provider         1620.00
           public_semi_public_service       1028.52
           small_medium_shop              224633.83
           specialized_shop               117859.88
2016-03-31 bulk_discount_shop                222.90
           market                           1807.68
           other                         3343801.43
           private_service_provider      1618965.82